spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://host.docker.internal:5432/e-government-access-control
    username: postgres
    password: 1234
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
        default_schema: e_gov_db
    show-sql: true
server:
  port: 8083