# Use the official PostgreSQL image as a base image
FROM postgres:latest

# Set environment variables
ENV POSTGRES_DB=e-gov-db
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=1234qwer

# Expose the default PostgreSQL port
EXPOSE 5432