version: '3'

services:
  db:
    build: ..
    ports:
      - "5432:5432"
    container_name: e-gov
    environment:
      POSTGRES_DB: e-gov-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234qwer
    volumes:
      - e-gov-db-data:/var/lib/postgresql/data

volumes:
  e-gov-db-data: