spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=e_gov_db
    username: postgres
    password: 1234
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
    show-sql: false
  cloud:
    openfeign:
      client:
        config:
          authentication-client:
            url: http://localhost:8081/api/v1
          access-control-client:
            url: http://localhost:8083/api/v1 

