name: Deploy

on:
  push:
    branches:
      - main

jobs:
  add_keys_and_execute_commands:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up environment variables
      run: |
        export POSTGRES_USER=ostgres
        export POSTGRES_PASSWORD=1234qwer
        export POSTGRES_DB=postgres
        export SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/postgres
        export SPRING_DATASOURCE_USERNAME=postgres
        export SPRING_DATASOURCE_PASSWORD=1234qwer
        
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Execute Python command
      run: |
        python manage.py start
