spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://host.docker.internal:5432/postgres?currentSchema=e_gov_auth
    username: postgres
    password: 1234qwer
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
    show-sql: false
server:
  port: 8081

keyPaths:
  privateKeyPath: src/main/resources/keys/private.pem
  publicKeyPath: src/main/resources/keys/public.pem
